@TicketingAPI_HostAddress = https://localhost:7017

GET {{TicketingAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

PUT {{TicketingAPI_HostAddress}}/ticketingapi/Create-Ticket
Content-Type: application/json

{
  "ticket_title":"First test ticket!",
  "ticket_description":"This is the description of the very first ticket inside of this application!"
}

###
